package com.vogella.tasks.events;

public interface MyEvent {
	String TOPIC_TODO = "TOPIC_TODOS";
	String TOPIC_TODO_ALLTOPICS = "TOPIC_TODOS/*";
	String TOPIC_TODOS_CHANGED = "TOPIC_TODOS/CHANGED";
	String TOPIC_TODO_NEW = "TOPIC_TODOS/TODO/NEW";
	String TOPIC_TODO_DELETE = "TOPIC_TODOS/TODO/DELETED";
	String TOPIC_TODO_UPDATE = "TOPIC_TODOS/TODO/UPDATED";
}
